//! Shell 集成：安装脚本或打印脚本。
//!
//! `pory --init-shell <shell>` **默认直接装到该 shell 的标准补全位置**（2026-09-21 改：
//! 这是用户主动运行的安装命令，让他自己去拼长路径 + 重定向是没必要的负担）。
//! 加 `--print` 则只打印到 stdout、不写任何文件 —— 给「想改短名 / 自己管理 /
//! 放到别处」的场景留口子，也让 `pory --init-shell zsh > some/_pory` 这类管道保持干净。
//!
//! 安装位置（按各 shell 的官方约定，尊重 `XDG_*` 环境变量）：
//! - fish：`~/.config/fish/completions/pory.fish`（fish 启动时自动加载该目录）
//! - bash：`~/.local/share/bash-completion/completions/pory`
//! - zsh：**不自动安装** —— 补全放哪由用户 `.zshrc` 里的 `$fpath` 决定，
//!   没有可安全假设的位置；改为打印脚本 + 在 stderr 说明怎么放。
//!
//! **覆盖保护**：目标文件已存在且不含本项目标记（`Generated by: pory --init-shell`）
//! 时拒绝写入并提示 —— 绝不覆盖有可能是用户手写的东西（与 `set_mode` 用
//! 文本级替换、不毁注释是同一条纪律）。
//!
//! ## 短名（`pr` → `pory`）在两个平台上用两种机制
//!
//! - **fish**：`abbr -a -- pr pory` 写在补全文件里 —— fish 启动时自动加载
//!   `completions/` 目录，所以**不需要也不应该碰任何 rc 文件**。
//! - **bash / zsh**：`alias pr=pory` **追加进 `~/.bashrc` / `~/.zshrc`**
//!   （2026-09-21 用户指定）。这两家的别名必须活在 rc 里才会在启动时生效，
//!   没有自动加载目录这种机制 —— 所以程序必须动 rc。
//!   动 rc 的三条纪律写在 `append_rc_block` 上：只追加、幂等、带可撤销的标记行。
//!
//! **注意 `pr` 与系统 POSIX 分页工具 `/usr/bin/pr` 同名**：
//! abbr / alias 都会在交互命令行里劫持它，要用真的 `pr` 得写 `\pr` 或 `command pr`。
//!
//! ## 验证状态（诚实标注）
//!
//! - `fish` 与 `bash`：**在本机真实 source 验证过**（注册结果逐条核对）。
//! - `zsh`：本机没有 zsh 二进制（只有 `/usr/share/zsh` 的补全残留），
//!   **未能实跑**。写法参照 `/usr/share/zsh/site-functions/` 下的真实文件
//!   （`#compdef` + `_arguments` + 末尾显式调用），但请把它当作「按规范书写、
//!   未经运行验证」。发现问题请反馈。

use crate::error::{PoryError, Result};
use crate::lang;
use std::path::{Path, PathBuf};

/// 本工具生成文件的标记。覆盖保护靠它区分「我们写的」与「用户自己的东西」。
const MARKER: &str = "Generated by: pory --init-shell";

/// 写进用户 rc 文件的标记行。
///
/// 两个用途：**幂等**（已存在就跳过，重复运行不会越加越多）与**可撤销**
/// （用户照着这行就能找到并删掉整块）。改 `~/.bashrc` / `~/.zshrc` 是侵入性
/// 最强的操作，这两条是底线。
const RC_MARKER: &str = "# pory: pr -> pory";

/// 执行 `--init-shell`：安装（补全文件 + rc 别名）或打印。返回要输出到 stdout 的文本。
///
/// 各 shell 的落点（2026-09-21 定稿，按用户要求）：
/// - **fish**：只写 `completions/pory.fish`（内含 abbr 短名 + 补全，fish 自动加载，不碰 rc）
/// - **bash**：写补全文件 **+ 往 `~/.bashrc` 追加一条 `alias pr=pory`**
/// - **zsh**：补全脚本打印到 stdout（无标准安装位置）**+ 往 `~/.zshrc` 追加同名别名**
pub fn run(shell: &str, print_only: bool) -> Result<String> {
    let script = integration(shell)?;

    // --print：只要脚本，不碰任何文件（含 rc）
    if print_only {
        return Ok(script);
    }

    match shell {
        "fish" => {
            let path = install_path("fish")?;
            write_checked(&path, &script)?;
            Ok(install_message("fish", &path, None))
        }
        "bash" => {
            let path = install_path("bash")?;
            write_checked(&path, &script)?;
            let (rc, added) = append_rc("bash")?;
            Ok(install_message("bash", &path, Some((&rc, added))))
        }
        "zsh" => {
            let (rc, added) = append_rc("zsh")?;
            // 说明走 stderr：`pory --init-shell zsh > _pory` 的 stdout 必须仍是一份干净脚本
            eprintln!("ℹ zsh 补全未自动安装：位置由你 .zshrc 里的 $fpath 决定。");
            eprintln!(
                "  把以上内容存为 `_pory` 放进 $fpath 的某个目录（例如 ~/.zsh/completions/），"
            );
            eprintln!("  并在 ~/.zshrc 里加：fpath=(~/.zsh/completions $fpath)");
            eprintln!(
                "  短名：{} —— {}",
                rc.display(),
                if added {
                    "已追加 alias pr=pory".to_string()
                } else {
                    format!("已有 `{RC_MARKER}` 标记，未重复追加")
                }
            );
            Ok(script)
        }
        other => Err(PoryError::Input(format!(
            "暂不支持 `{other}`。可用的 shell：fish / bash / zsh"
        ))),
    }
}

/// 解析 shell 的 rc 文件路径（bash → `~/.bashrc`，其余 → `~/.zshrc`）。
///
/// 别名要给**交互式 shell** 用，所以是 `.bashrc` —— `.bash_profile` 只在登录
/// shell 里读，把它当目标会让「开个新终端没有短名」这种玄学问题出现。
fn rc_path_for(shell: &str) -> Result<PathBuf> {
    let dirs =
        directories::BaseDirs::new().ok_or_else(|| PoryError::Config("无法定位用户目录".into()))?;
    Ok(match shell {
        "bash" => dirs.home_dir().join(".bashrc"),
        _ => dirs.home_dir().join(".zshrc"),
    })
}

/// 往指定 rc 文件追加 pory 别名块（**幂等**）。返回是否新写入。
///
/// 三条纪律：
/// 1. **只追加、绝不改写** —— rc 是人手写的配置，任何重排都可能踩到用户的逻辑；
/// 2. **幂等**：检测到标记行就跳过，重复运行不会越加越多；
/// 3. **补换行**：原文件结尾没有换行符时先补一个，否则别名会和上一行粘成一句。
///
/// 拆成「传路径」的形态是为了可测：单测用临时文件验证，**绝不碰真实 HOME**。
fn append_rc_block(rc: &Path, shell: &str) -> Result<bool> {
    let existing = std::fs::read_to_string(rc).unwrap_or_default();
    if existing.contains(RC_MARKER) {
        return Ok(false);
    }

    let mut block = String::new();
    if !existing.is_empty() && !existing.ends_with('\n') {
        block.push('\n');
    }
    block.push_str(&format!(
        "{RC_MARKER} (added by `pory --init-shell {shell}`; delete this line and the next to undo)\n\
         alias pr=pory\n"
    ));

    use std::io::Write;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(rc)
        .map_err(|e| PoryError::Config(format!("无法打开 {}：{e}", rc.display())))?;
    f.write_all(block.as_bytes())
        .map_err(|e| PoryError::Config(format!("写入 {} 失败：{e}", rc.display())))?;

    Ok(true)
}

/// 把 rc 追加与路径解析组合起来（`--init-shell` 用）。
fn append_rc(shell: &str) -> Result<(PathBuf, bool)> {
    let rc = rc_path_for(shell)?;
    let added = append_rc_block(&rc, shell)?;
    Ok((rc, added))
}

/// 移除 pory 装过的 shell 集成：补全文件 + rc 里的别名块。
///
/// 返回逐项报告（每行一条），**只报告实际发生的事** —— 没装过的说「不存在，跳过」，
/// 别人的文件说「不是 pory 生成的，未动」。卸载命令的价值有一半在于
/// 让人看清「到底动了什么」，报喜不报忧等于抹掉这个价值。
pub fn remove_integration() -> Result<Vec<String>> {
    let mut report = Vec::new();

    // ── 1. 补全文件（fish / bash）──
    // 只删含本项目标记的；同名文件若是用户手写的，绝不碰（与写入时同一条纪律）
    for shell in ["fish", "bash"] {
        let Ok(path) = install_path(shell) else {
            continue;
        };
        if !path.exists() {
            continue; // 没装过，静默跳过（卸载时不必逐条念「你没装 fish」）
        }
        let content = std::fs::read_to_string(&path).unwrap_or_default();
        if !content.contains(MARKER) {
            report.push(format!(
                "⚠ {} 不是 pory 生成的，未动：{}",
                shell,
                path.display()
            ));
            continue;
        }
        match std::fs::remove_file(&path) {
            Ok(()) => report.push(format!("✓ 已删除 {shell} 补全文件：{}", path.display())),
            Err(e) => report.push(format!("⚠ 删除 {} 失败：{e}", path.display())),
        }
    }

    // ── 2. rc 里的别名块（bash / zsh）──
    for shell in ["bash", "zsh"] {
        let Ok(rc) = rc_path_for(shell) else {
            continue;
        };
        if !rc.exists() {
            continue;
        }
        // 没写过的情况静默跳过（卸载时不必逐条念「没装过 zsh」）
        if remove_rc_block(&rc)? {
            report.push(format!("✓ 已从 {} 移除别名", rc.display()));
        }
    }

    if report.is_empty() {
        report.push("· 没有发现 pory 装过的 shell 集成".to_string());
    }

    Ok(report)
}

/// 从 rc 文件里删掉 pory 别名块（标记行 + 紧随的 `alias pr=pory`）。返回是否发生删除。
///
/// 只删除**我们写的那两行**，其余内容逐行原样重建 ——
/// 判据是标记行 + 下一行严格等于 `alias pr=pory`（用户改过别名的那行就不动，
/// 宁可留下它让用户自己看，也不误删别人的东西）。
fn remove_rc_block(rc: &Path) -> Result<bool> {
    let content = std::fs::read_to_string(rc).unwrap_or_default();
    if !content.contains(RC_MARKER) {
        return Ok(false);
    }

    let mut out = String::with_capacity(content.len());
    let mut lines = content.lines().peekable();
    while let Some(line) = lines.next() {
        if line.trim_start().starts_with(RC_MARKER) {
            // 我们写的别名行紧随其后 —— 一并吃掉（用户改过内容就不吃，留给用户）
            if lines.peek().map(|l| l.trim()) == Some("alias pr=pory") {
                lines.next();
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }

    // `lines()` 丢掉了「原文是否以换行结尾」的信息：原文不以换行结尾时，
    // 重建会多出一个换行，去掉它，尽量还原用户文件的原貌。
    if !content.ends_with('\n') {
        out.pop();
    }

    std::fs::write(rc, out)
        .map_err(|e| PoryError::Config(format!("写入 {} 失败：{e}", rc.display())))?;
    Ok(true)
}

/// 按 shell 的标准位置算安装路径（尊重 XDG 变量）。
fn install_path(shell: &str) -> Result<PathBuf> {
    let dirs =
        directories::BaseDirs::new().ok_or_else(|| PoryError::Config("无法定位用户目录".into()))?;
    Ok(match shell {
        // fish 启动时自动加载该目录下的补全
        "fish" => dirs.config_dir().join("fish/completions/pory.fish"),
        // bash-completion 的官方用户级目录（bash-completion 包会自动加载）
        "bash" => dirs.data_dir().join("bash-completion/completions/pory"),
        other => {
            return Err(PoryError::Input(format!(
                "`{other}` 没有可自动安装的补全位置。可用的 shell：fish / bash（zsh 请用 --print）"
            )))
        }
    })
}

/// 带覆盖保护地写入脚本。
fn write_checked(path: &Path, script: &str) -> Result<()> {
    // 已存在 → 只允许覆盖本项目生成的文件
    if path.exists() {
        let old = std::fs::read_to_string(path).unwrap_or_default();
        if !old.contains(MARKER) {
            return Err(PoryError::Config(format!(
                "{} 已存在，且不是 pory 生成的（未覆盖）。确认要替换就先手动删掉它。",
                path.display()
            )));
        }
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| PoryError::Config(format!("无法创建目录 {}：{e}", parent.display())))?;
    }

    std::fs::write(path, script)
        .map_err(|e| PoryError::Config(format!("写入 {} 失败：{e}", path.display())))
}

/// 安装成功后的反馈。内容按 shell 分档 —— 它们的「别名怎么生效」机制完全不同：
///
/// - **fish**：`completions/` 目录里的代码（含 `abbr`）启动时自动执行 → 短名与补全
///   一体生效，不碰任何 rc 文件。
/// - **bash**：补全文件由 **bash-completion 包**懒加载（前提是该包存在）；
///   短名不依赖它 —— 直接追加进 `~/.bashrc` 的 `alias`，新开终端即生效。
/// - **zsh**：补全脚本走 stdout 由用户安置；短名同 bash，追加进 `~/.zshrc`。
fn install_message(shell: &str, path: &Path, rc: Option<(&Path, bool)>) -> String {
    let mut msg = String::new();

    match shell {
        "fish" => {
            msg.push_str(&format!(
                "✓ 已安装 fish 补全（含短名 pr → pory）：{}\n",
                path.display()
            ));
            msg.push_str("  新开一个终端生效（当前终端可先 source 该文件）。\n");
            msg.push_str("  短名由文件里的 abbr 提供（要用系统 pr 就敲 \\pr）。\n");
            msg.push_str(&format!(
                "  卸载：删掉这个文件即可；想自己管理用：pory --init-shell {shell} --print"
            ));
        }
        _ => {
            msg.push_str(&format!("✓ 已安装 bash 补全文件：{}\n", path.display()));
            if let Some((rc, added)) = rc {
                msg.push_str(&format!(
                    "  {}：{}\n",
                    rc.display(),
                    if added {
                        format!("已追加短名（标记行 `{RC_MARKER}`）")
                    } else {
                        format!("已有 `{RC_MARKER}` 标记，未重复追加")
                    }
                ));
            }
            msg.push_str("  短名不依赖补全：`alias pr=pory` 已进 rc，新开终端即生效。\n");
            msg.push_str(
                "  注意：bash 补全还需要 bash-completion 包才会加载（Arch: pacman -S bash-completion）。\n",
            );
            msg.push_str(&format!(
                "  卸载：删掉补全文件 + rc 里以 `{RC_MARKER}` 开头的那两行；想自己管理用：pory --init-shell {shell} --print"
            ));
        }
    }

    msg
}

/// 生成某个 shell 的集成脚本文本。
///
/// 语言候选从 `lang::aliases()`（即 SUPPORTED 表）注入 —— 补全与解析器共用
/// 同一份数据源，不会出现「补全里有、实际不认」的漂移。
pub fn integration(shell: &str) -> Result<String> {
    let langs = lang::aliases().join(" ");
    let script = match shell {
        "fish" => FISH.replace("__LANGS__", &langs),
        "bash" => BASH.replace("__LANGS__", &langs),
        "zsh" => ZSH.replace("__LANGS__", &langs),
        other => {
            return Err(PoryError::Input(format!(
                "暂不支持 `{other}`。可用的 shell：fish / bash / zsh"
            )))
        }
    };
    Ok(script)
}

/// fish 集成：abbr（输入时展开，自文档化）+ 参数补全。
const FISH: &str = r#"# pory — fish shell integration
# Generated by: pory --init-shell fish
#
# Installed by: pory --init-shell fish
# Update:       pory --init-shell fish          (rewrites this file)
# Preview:      pory --init-shell fish --print  (prints without installing)
# Uninstall:    delete this file. It touches nothing else.

# Short name: typing "pr" then space expands to "pory".
# NOTE: /usr/bin/pr (POSIX paginator) shares this name — in an interactive shell
# it gets expanded to pory. Type "\pr" or "command pr" to reach the real one.
# Delete this line if you don't want the short name.
abbr -a -- pr pory

# ── Option completions ──
complete -c pory -s t -l target -x -a "__LANGS__" -d "Target language"
complete -c pory -s f -l from -x -a "auto __LANGS__" -d "Source language (default: auto)"
complete -c pory -s b -l backend -x -a "ai traditional" -d "Translation mode"
complete -c pory -l plain -d "Print the translation only: no color, no footnote, no animation"
complete -c pory -l no-cache -d "Skip the cache for this call"
complete -c pory -l refresh -d "Ignore existing cache and re-translate"
complete -c pory -l timeout -r -d "Overall translation limit in seconds"
complete -c pory -l clear-cache -d "Clear the translation cache and exit"
complete -c pory -l init -d "Write a sample config file and exit"
complete -c pory -l init-shell -x -a "fish bash zsh" -d "Install shell integration and exit"
complete -c pory -s h -l help -d "Print help"
complete -c pory -s V -l version -d "Print version"
"#;

/// bash 集成：纯参数补全（`complete -F`），**不含短名**。
///
/// 用 `case "$prev"` 分派取值型参数，其余情况列出全部选项 —— 简单、无外部依赖。
///
/// ⚠️ **前提必须让用户知道**（本机实测 2026-09-21：Arch 默认不装 bash-completion）：
/// 本文件要由 **bash-completion 包**懒加载才会执行 —— 没装包时补全不生效。
const BASH: &str = r#"# pory — bash completion
# Generated by: pory --init-shell bash
#
# Installed by: pory --init-shell bash
# Update:       pory --init-shell bash          (rewrites this file)
# Preview:      pory --init-shell bash --print  (prints without installing)
# Uninstall:    delete this file. It touches nothing else.
#
# Requires the bash-completion package for bash to load this file at all.

_pory_complete() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    case "$prev" in
        -t|--target)
            COMPREPLY=( $(compgen -W "__LANGS__" -- "$cur") )
            return ;;
        -f|--from)
            COMPREPLY=( $(compgen -W "auto __LANGS__" -- "$cur") )
            return ;;
        -b|--backend)
            COMPREPLY=( $(compgen -W "ai traditional" -- "$cur") )
            return ;;
        --init-shell)
            COMPREPLY=( $(compgen -W "fish bash zsh" -- "$cur") )
            return ;;
        --timeout)
            COMPREPLY=( $(compgen -W "60 300 600 900" -- "$cur") )
            return ;;
    esac

    COMPREPLY=( $(compgen -W "-t --target -f --from -b --backend \
-timeout --plain --no-cache --refresh --clear-cache --init --init-shell --print \
-h --help -V --version" -- "$cur") )
}

complete -F _pory_complete pory
"#;

/// zsh 集成：alias + `#compdef` 补全。
///
/// ⚠️ 本机无 zsh，**未实跑验证**（见模块头注释）。写法对照
/// `/usr/share/zsh/site-functions/` 下真实文件：`#compdef` 首行声明归属，
/// `_arguments` 描述选项，末尾显式调用自身。
/// 注意 `#compdef` 只在文件名为 `_pory` 且位于 `$fpath` 时生效，
/// `source` 它不会注册补全 —— 这一点写进了脚本注释。
const ZSH: &str = r#"#compdef pory
# pory — zsh completion
# Generated by: pory --init-shell zsh
#
# NOTE: pory does not install zsh completions automatically — where completion
#       files live is decided by your $fpath. This script is printed instead:
#
#   pory --init-shell zsh > ~/.zsh/completions/_pory
#   then in ~/.zshrc:  fpath=(~/.zsh/completions $fpath)
#                      autoload -Uz compinit && compinit
#
# Uninstall: delete the file. This script touches nothing else.
# NOTE: #compdef only works when the file is named _pory and lives in $fpath.
#       `source <(pory --init-shell zsh)` does NOT register it as a completion.

_pory() {
    _arguments -s \
        '(-t --target)'{-t,--target}'[Target language]:language:(__LANGS__)' \
        '(-f --from)'{-f,--from}'[Source language (default: auto)]:language:(auto __LANGS__)' \
        '(-b --backend)'{-b,--backend}'[Translation mode]:mode:(ai traditional)' \
        '--timeout[Overall translation limit in seconds]:seconds:' \
        '--plain[Print the translation only: no color, no footnote, no animation]' \
        '--no-cache[Skip the cache for this call]' \
        '--refresh[Ignore existing cache and re-translate]' \
        '--clear-cache[Clear the translation cache and exit]' \
        '--init[Write a sample config file and exit]' \
        '--init-shell[Install shell integration and exit]:shell:(fish bash zsh)' \
        '(-h --help)'{-h,--help}'[Print help]' \
        '(-V --version)'{-V,--version}'[Print version]' \
        '*:text to translate:'
}

_pory "$@"
"#;

#[cfg(test)]
mod tests {
    use super::*;

    /// 脚本体里的短名只在 fish（bash/zsh 的别名走 rc 文件，不在脚本里）
    #[test]
    fn 脚本体里的短名只在_fish() {
        let fish = integration("fish").unwrap();
        assert!(fish.contains("abbr -a -- pr pory"), "fish 缺短名");
        assert!(fish.contains("complete -c pory -s t"), "fish 缺 -t 补全");

        let bash = integration("bash").unwrap();
        assert!(!bash.contains("alias pr"), "bash 不该有短名");
        assert!(
            bash.contains("complete -F _pory_complete pory"),
            "bash 缺注册"
        );
        assert!(bash.contains("ai traditional"), "bash 缺模式候选");

        let zsh = integration("zsh").unwrap();
        assert!(!zsh.contains("alias pr"), "zsh 不该有短名");
        assert!(zsh.contains("#compdef pory"), "zsh 缺 compdef 声明");
        assert!(zsh.contains("_arguments"), "zsh 缺 _arguments");
        assert!(zsh.contains("ai traditional"), "zsh 缺模式候选");
    }

    /// 语言候选必须与解析器同源 —— 补全里有、实际不认（或反之）都是 bug
    #[test]
    fn 语言候选与解析器同源() {
        let aliases = lang::aliases();
        for shell in ["fish", "bash", "zsh"] {
            let s = integration(shell).unwrap();
            for a in &aliases {
                assert!(s.contains(*a), "{shell} 补全缺语种 {a}");
            }
        }
    }

    /// pr 与系统 pr 的冲突必须在 fish 脚本里写明绕过方式 ——
    /// 这是用户知情选择的前提，注释丢了就等于静默劫持
    /// （bash/zsh 不做短名，自然无此提示）
    #[test]
    fn fish_脚本提示_pr_冲突与绕过() {
        let s = integration("fish").unwrap();
        assert!(s.contains(r#"\pr"#), "fish 未提示绕过写法 \\pr");
        assert!(s.contains("POSIX"), "fish 未说明 pr 的系统占用");
    }

    /// 未知名明确报错并列出可选项
    #[test]
    fn 未支持的_shell_报错() {
        let msg = match integration("powershell") {
            Ok(_) => panic!("powerhell 不支持，不该输出脚本"),
            Err(e) => e.to_string(),
        };
        assert!(msg.contains("fish"), "报错要指出现有可用项：{msg}");
        assert!(msg.contains("bash") && msg.contains("zsh"), "{msg}");
    }

    // ── 安装逻辑 ──

    /// 安装路径要落在各 shell 的官方约定位置
    #[test]
    fn 安装路径符合约定() {
        let fish = install_path("fish").unwrap();
        assert!(
            fish.ends_with("fish/completions/pory.fish"),
            "实际：{}",
            fish.display()
        );
        let bash = install_path("bash").unwrap();
        assert!(
            bash.ends_with("bash-completion/completions/pory"),
            "实际：{}",
            bash.display()
        );
        // 不在支持列表里的（含 zsh）没有可自动安装的位置
        assert!(install_path("zsh").is_err());
        assert!(install_path("powershell").is_err());
    }

    /// 覆盖保护：**不是我们生成的文件绝不覆盖**（可能是用户手写的）
    #[test]
    fn 拒绝覆盖非本项目文件() {
        let dir = std::env::temp_dir().join(format!("pory-shell-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("not-ours.fish");
        std::fs::write(&path, "# 用户手写的东西\n").unwrap();

        let err = write_checked(&path, "# pory 脚本").unwrap_err().to_string();
        assert!(err.contains("不是 pory 生成的"), "实际：{err}");
        // 内容必须原封不动
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "# 用户手写的东西\n"
        );

        // 我们生成的文件（含标记）→ 允许覆盖（重新生成的自然语义）
        let ours = dir.join("ours.fish");
        std::fs::write(&ours, format!("# {MARKER} fish\n旧内容\n")).unwrap();
        write_checked(&ours, "新内容").unwrap();
        assert_eq!(std::fs::read_to_string(&ours).unwrap(), "新内容");

        std::fs::remove_dir_all(&dir).ok();
    }

    /// --print 与 zsh 都只输出脚本、不碰文件系统
    #[test]
    fn print_与_zsh_都不写文件() {
        let printed = run("fish", true).unwrap();
        assert!(printed.contains(MARKER), "print 模式应原样输出脚本");

        let zsh = run("zsh", false).unwrap();
        assert!(zsh.contains("#compdef pory"), "zsh 走打印路径");
    }

    /// 安装反馈必须包含：路径、生效方式、短名（含冲突绕行）、卸载、自助出口；
    /// bash 还要说清「rc 里加了别名」与「补全需要 bash-completion 包」
    #[test]
    fn 安装反馈信息完整() {
        let fish = install_message("fish", Path::new("/tmp/x/pory.fish"), None);
        assert!(fish.contains("/tmp/x/pory.fish"), "缺路径");
        assert!(fish.contains("新开一个终端"), "缺生效方式");
        assert!(fish.contains(r#"\pr"#), "缺短名冲突绕行");
        assert!(fish.contains("卸载"), "缺卸载说明");
        assert!(fish.contains("--print"), "缺自助管理出口");

        let bash = install_message(
            "bash",
            Path::new("/tmp/x/pory"),
            Some((Path::new("/tmp/x/.bashrc"), true)),
        );
        assert!(bash.contains("/tmp/x/pory"), "缺补全文件路径");
        assert!(bash.contains("/tmp/x/.bashrc"), "缺 rc 路径");
        assert!(bash.contains("alias pr=pory"), "缺 rc 里加的那条别名");
        assert!(bash.contains("bash-completion"), "缺补全的包前提说明");
        assert!(bash.contains(RC_MARKER), "缺标记行（用户靠它撤销）");

        // 已加过 → 明确说「未重复追加」，别让用户以为又写了一遍
        let again = install_message(
            "bash",
            Path::new("/tmp/x/pory"),
            Some((Path::new("/tmp/x/.bashrc"), false)),
        );
        assert!(again.contains("未重复追加"), "实际：{again}");
    }

    // ── rc 追加（用临时文件测，绝不碰真实 HOME）──

    /// 追加：保住原内容、补换行、幂等、不重复
    #[test]
    fn rc_追加幂等且不破坏原内容() {
        let dir = std::env::temp_dir().join(format!("pory-rc-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rc = dir.join(".bashrc");
        // 故意不以换行结尾 —— 顺手覆盖「补换行」这条边界
        std::fs::write(&rc, "# 我的配置\nexport FOO=1").unwrap();

        assert!(append_rc_block(&rc, "bash").unwrap(), "首次应写入");
        let after = std::fs::read_to_string(&rc).unwrap();
        assert!(
            after.starts_with("# 我的配置\nexport FOO=1\n"),
            "原文必须保留，且和别名之间要补上换行：{after}"
        );
        assert!(after.contains(RC_MARKER), "缺标记行");
        assert!(after.contains("alias pr=pory"), "缺别名");
        assert_eq!(after.matches("alias pr=pory").count(), 1, "只应有一条别名");

        // 幂等：第二次跳过、内容零变化
        assert!(!append_rc_block(&rc, "bash").unwrap(), "第二次应跳过");
        assert_eq!(std::fs::read_to_string(&rc).unwrap(), after);

        std::fs::remove_dir_all(&dir).ok();
    }

    /// rc 不存在 → 创建；新文件直接以标记行开头（不留多余空行）
    #[test]
    fn rc_不存在时创建() {
        let dir = std::env::temp_dir().join(format!("pory-rc-new-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rc = dir.join(".zshrc");

        assert!(append_rc_block(&rc, "zsh").unwrap());
        let s = std::fs::read_to_string(&rc).unwrap();
        assert!(s.starts_with(RC_MARKER), "新文件应直接以标记行开头：{s}");
        assert!(s.contains("alias pr=pory"), "缺别名");

        std::fs::remove_dir_all(&dir).ok();
    }

    // ── 卸载 ──

    /// 卸载只删我们那两行，前后内容逐行原样保留
    #[test]
    fn 卸载只删别名块其余原样() {
        let dir = std::env::temp_dir().join(format!("pory-rm-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rc = dir.join(".bashrc");
        std::fs::write(
            &rc,
            format!(
                "# 我的配置\nexport FOO=1\n{RC_MARKER} (added by `pory --init-shell bash`; delete this line and the next to undo)\nalias pr=pory\n# 我后来又加的一行\nexport BAR=2\n"
            ),
        )
        .unwrap();

        assert!(remove_rc_block(&rc).unwrap(), "有标记应发生删除");
        let after = std::fs::read_to_string(&rc).unwrap();
        assert!(!after.contains(RC_MARKER), "标记行应删掉");
        assert!(!after.contains("alias pr=pory"), "别名行应删掉");
        assert!(
            after.contains("# 我的配置"),
            "用户原有内容必须保留：{after}"
        );
        assert!(after.contains("export FOO=1"), "{after}");
        assert!(
            after.contains("# 我后来又加的一行") && after.contains("export BAR=2"),
            "用户后加的内容必须保留：{after}"
        );

        // 再删一次：没有标记 → 返回 false，不写文件
        assert!(!remove_rc_block(&rc).unwrap(), "无标记应返回 false");

        std::fs::remove_dir_all(&dir).ok();
    }

    /// 用户把别名行改成了别的 → 只删标记行，那一行留着（不误删别人的东西）
    #[test]
    fn 卸载不误删用户改过的别名行() {
        let dir = std::env::temp_dir().join(format!("pory-rm2-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rc = dir.join(".zshrc");
        std::fs::write(&rc, format!("{RC_MARKER} (added by `x`)\nalias pp=pory\n")).unwrap();

        assert!(remove_rc_block(&rc).unwrap());
        let after = std::fs::read_to_string(&rc).unwrap();
        assert!(!after.contains(RC_MARKER), "标记行应删掉");
        assert!(after.contains("alias pp=pory"), "用户改过的行不删：{after}");

        std::fs::remove_dir_all(&dir).ok();
    }
}
